### ISSUE TITLE
Customer Filters - Not available in Wizard

### ISSUE THREAD

**Issue by gmparky** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#113]
I am following this guide but there is no Filters section in the wizard, this is for an Azure SQL Connector. Could you please advise how to add in filters?

![image](https://user-images.githubusercontent.com/40665509/101638816-77eb2700-3a26-11eb-88b4-2dfe639e31d1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c1b924-ef47-230c-ea15-648cd525b850
* Version Independent ID: 1761c8f2-9a84-52c4-27a2-4fce1cba62d6
* Content: [Manage custom filters](https://docs.microsoft.com/en-us/microsoftsearch/custom-filters)
* Content Source: [MicrosoftSearch/custom-filters.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/custom-filters.md)
* Service: **mssearch**
* GitHub Login: @RodHB
* Microsoft Alias: **rodhb**

**Comment by jypal6** [comment]
We would need more information from you to figure out the root cause for this. Can you please submit this issue via the 'Feedback' option in Microsoft 365 admin center. Also, please ensure you have selected the option for us to contact you. 
![image](https://user-images.githubusercontent.com/33307111/101801550-7c056a80-3b34-11eb-9e5d-fa2f9d0ed820.png)

**Comment by jypal6** [comment]
@gmparky Can you please reach out to us as indicated in the above response to help resolve your issue.

**Comment by gmparky** [comment]
Hi. I have raised a ticket via our Premium support Case #:23253154

**Comment by TracyGH** [comment]
@gmparky - We are facing the same issue.  Did you get any clarity from support?  Below is the email I sent to our premiere account manager, but I haven't gotten any traction.  

-------------------------------------------------------------------
I need some assistance defining what qualifies as a 'managed property' in M365 search.  I'm trying to create additional filters in a custom search vertical.  According to the limitations listed in the [documentation](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoftsearch%2Fcustom-filters&data=04%7C01%7Ckyouells%40microsoft.com%7Ce6a64395274344a3ac0108d8ca22604a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637481596288568784%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KLdpIJIQ6NJb08BoLw29WUuyjr2E3qZU%2B3cPR%2FGvzto%3D&reserved=0):  "You can currently create filters only on string & date type managed properties."  But it's unclear what exactly is a managed property.  

Of the fields I'm pulling into my connector with the SQL query, only 1 is 'refinable' (see attached), and that's the only one available to add as a filter in my associated vertical.

There is a step in the connection wizard called Property Labels (see attached).  I'm 'guessing' a subset of those are the only available (refinable) managed properties at this time.  And if that is the case, is it possible to retrieve the 'StringCollection' datatype listed for the Authors property label with a SQL query/source?

**Comment by maheshsinghania** [comment]
@TracyGH thanks for reaching out.
Property Labels are fixed set of attributes used in Microsoft search for easy mapping to default experiences.
The UI "Assign Property labels" allows the tenant admin to define best possible match from the connector schema to these fixed system properties. Fixed property "Authors" is unable to map to any available SQL Schema property, 

On your earlier point on refinable (filter-able) properties. Only StringCollection and DateTime schema properties are available to be used as refiners. We are working on support for other data types (single valued string and integers) currently.

Since your schema (from the screenshot) contains CreatedDateTime as a DateTime property it is available to be chosen as a refinable attribute.  Other schema attributes listed are data type "string" (and not stringCollection) hence not refinable.

**Comment by TracyGH** [comment]
Thanks @maheshsinghania!  Do you know where to find information regarding how to configure the SQL query in my search connector so it recognizes StringCollection types versus String types?

**Comment by maheshsinghania** [comment]
@TracyGH - Yes, you are right. Currently only DateTime will be configurable as the SQL connector maps varchar data type to String (and not StringCollection). 
That said, String and integer data types will soon be refinable. Will keep you posted on this.

**Comment by gmparky** [comment]
@TracyGH  After a lot of investigation we where advised it wasn't released yet for String Filters but is supposed to be coming in March. Take that with a pinch of salt as it's been hard to keep track of all the moving parts for this. Verticals have only just reached GA in our tenant and we can only build refiners on date time fields.
