### ISSUE TITLE
Integrate MS Search/Bing Search bar into another application

### ISSUE THREAD

**Issue by leonzwinderman** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#164]
Would it be possible to integrate the Microsoft Search or even the Bing Search bar into another application with an API?

**Comment by dawholl** [comment]
@leonzwinderman I'm assuming you've seen this article about embedding a [Microsoft Search search box in a SharePoint or intranet site](https://docs.microsoft.com/microsoftsearch/add-a-search-box-to-your-intranet-site) and this site with [documentation about Bing Search APIs](https://docs.microsoft.com/azure/cognitive-services/bing-web-search/) and they aren't applicable because 1. you want to add a search box to an app, not a website and 2. you want to only return internal org results or a combination of internal and web results.

If these assumptions are wrong, please let me know. 

I'll reach out to my Microsoft Search in Bing team members and find out if there's any information that we can share about a Microsoft Search in Bing API/inclusion of org results in the Bing Web Search API or the Bing Custom Search API.

**Comment by dawholl** [comment]
@leonzwinderman, for info about the Microsoft Search API, see [Overview of the Microsoft Search API in Microsoft Graph](https://docs.microsoft.com/graph/search-concept-overview).

**Comment by leonzwinderman** [comment]
@dawholl 
Hi Dawholl,

Thank you for the reply. I wanted to know if I can integrate the UI/Search bar of MS Search into an web based application. So users of the web based application can f.e. search in their Office documents.

BR,
Leon

**Comment by dawholl** [comment]
@leonzwinderman, according to the [overview topic](https://docs.microsoft.com/en-us/graph/search-concept-overview), "You can use the Microsoft Search API in Microsoft Graph to extend Microsoft Search to your apps." 

This page also links to the [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) where you can make Graph API requests (there's a section for Search) and see responses and the [Graph Q&A](https://docs.microsoft.com/answers/products/m365#microsoft-graph) site where you can find answers to technical questions.

I believe this info answers your initial question and am closing this issue with this comment.
