### ISSUE TITLE
Soft-deleted column type doesn't support Boolean 

### ISSUE THREAD

**Issue by puthurr** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#231]
Skipping soft-deleted rows (Optional) doesn't mention the pre-requisite that the column type has to be a string. The SQL connector doesn't accept a Boolean-type soft-deleted column.

Let us know if we could document that type restriction in our documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b069776-85d6-8e77-db4f-061ef6e558f1
* Version Independent ID: ee77b097-5c80-43f9-935a-c225740af80e
* Content: [Azure SQL and Microsoft SQL Server Graph connector for Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/mssql-connector?source=docs#step-3b-incremental-crawl-optional)
* Content Source: [MicrosoftSearch/MSSQL-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/MSSQL-connector.md)
* Service: **mssearch**
* GitHub Login: @mecampos
* Microsoft Alias: **mecampos**

**Comment by mecampos** [comment]
Hello @puthurr, thank you for bringing this up. I am currently reviewing the article and will follow up internally to confirm if an update is needed on the instructions.
In your case, to confirm the expected behavior of that field please send an email to: MicrosoftGraphConnectorsFeedback@service.microsoft.com, including your tenant Id and reference this issue. Our Engineers will be able to confirm the restriction.
