### ISSUE TITLE
Access Level instructions are incomplete

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#25]
Please provide information about how access levels for Teams, Yammer, and services other than SharePoint work with Microsoft Search. Everyone of the content sources needs to be addressed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1df67176-e302-f972-dbf7-d7e0747e5bd2
* Version Independent ID: e213129d-0fb1-31ee-a654-091d032c2746
* Content: [Set up **Microsoft Search**](https://docs.microsoft.com/en-us/microsoftsearch/setup-microsoft-search)
* Content Source: [MicrosoftSearch/setup-microsoft-search.md](https://github.com/MicrosoftDocs/OfficeDocs-MicrosoftSearch/blob/public/MicrosoftSearch/setup-microsoft-search.md)
* Service: **mssearch**
* GitHub Login: @adefowler
* Microsoft Alias: **anfowler**

**Comment by adefowler** [comment]
Thank you for taking the time to provide feedback! The documentation says that we honor the content source's permissions. We don't explicitly state the access levels because we can't control them from Microsoft Search. But I do see what you're talking about...that we link off to the SharePoint permissions documentation, but don't link to additional content sources. I will update this content to include those links. It may take a bit to track down the info. I'll reply when it's updated.

**Comment by adefowler** [comment]
@DeanGross - The topic has been updated with this information. Thank you!
