### ISSUE TITLE
Enabling connector on Company tenant

### ISSUE THREAD

**Issue by nehapallod** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#31]
We would like Connector to be enabled on our Tenant, please suggest a person who can help us do so.

**Comment by monaray97** [comment]
Hi @nehapallod, did you/your organization submit the Microsoft Graph Connectors Public Preview form?

**Comment by nehapallod** [comment]
Yes it has been submitted, but there is an urgency in terms of getting started and the process takes one week of time. Is there anyway you can help us expedite.

Thanks,
Neha Pallod

**Comment by monaray97** [comment]
Hi @nehapallod, our team is currently looking through our form submissions and will enable connector functionality for those tenants in waves. Please tell the person who submitted the form to keep an eye on their email since we will be notifying you when your tenant has this functionality via our email address MicrosoftGraphConnectorsFeedback@service.microsoft.com. Thank you for your patience!
