### ISSUE TITLE
Inaccurate Instructions in Documentation 

### ISSUE THREAD

**Issue by billdiekmann** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#46]
I have been trying to get the Floor Plan & Location setup to work, but never successfully maps a user.

1. Create a location (Called: Building 2) with all required info
2. Add Floorplan
   a. In AAD, user "Office" is B2/1340"
   b. Select Building dropdown, select Building 2
   c. Upload File (upload a .dwg, created from visio, with two labels (B2 1340 & B2 1341)
   d. After upload, you are required to identify a floor and/or wing (I set Floor: 1)
   e. Link Office Locations: Enter your Location AAD code. Through trial and error, I successfully set this code to "B2"
   f. Specify location patterns: I set floor to "1" and room to "340"
   g. Ready to go: no users were mapped; Selecting the Details of the uploaded file, I am presented with both of my drawing labels "B2 1340" & "B2 1341", with no entry in the Employee Seat

No variation of step e or f result in a different outcome.

Documentation errors or omissions:
1. To get the labels to work from Visio, you must define the "Shape Data" for the label. Specifically you need to have the following label properties:
Building Code:
Floor:
Room number:

In my example above the values would be
Building code: B2
Floor: 1
Room number: 340

2. In the doc https://docs.microsoft.com/en-us/microsoftsearch/floorplans-bestpractices, Section "User account office location"
Best practice is to "Include a separator **after building codes and floors**.", but the example explanation is "**Separate building codes from floor and room numbers** with a separator or a space, as in these examples:
B1 1001
B1/1001
B1-1001"

The Best practice does not match the example, so we do not know which is correct.

None of my efforts has successfully mapped a user to a map location

**Comment by rasrivas-ms** [comment]
Hi,

Thanks for trying out the scenario. I would suggest the following _changes_ to make the scenario work. After the two changes are made in step (a) and (c), the scenario should work. Rest of the steps should work as is.

Add Floorplan
a. In AAD, user "Office" is B2/1340" 
_Please add data for 11 users. May be something like B2/1340, B2/1341, B2/1342, B2/1343 ... B2/1351. It takes sometime for the office changes to propagate to Microsoft Search. Therefore, before trying another upload, please search for the profiles on Office.com, SPO or Bing and ensure the Office locations are updated to the values shown above. 
We need 11 users because we try to match a minimum number of people to a floor. This minimum number is set to 10 today._
b. Select Building dropdown, select Building 2
c. Upload File (upload a .dwg, created from visio, with two labels (B2 1340 & B2 1341)
_Add 11 labels corresponding to the 11 users in (a). Number them B2/1340 to B2/1351. Please notice that '/' is used instead of a space._
d. After upload, you are required to identify a floor and/or wing (I set Floor: 1)
e. Link Office Locations: Enter your Location AAD code. Through trial and error, I successfully set this code to "B2"
f. Specify location patterns: I set floor to "1" and room to "340"
g. Ready to go: no users were mapped; Selecting the Details of the uploaded file, I am presented with both of my drawing labels "B2 1340" & "B2 1341", with no entry in the Employee Seat

**Comment by billdiekmann** [comment]
Thanks for the additional information (which I hope makes it into the documentation)

I modified the values in the "Office" field to B2/1340 (etc)(Building/FloorRoom)
I set 15 accounts with location mappings the same way
Modified the Visio drawing to include more office labels (approximately 30)
Saved the file as a .dwg 
Verified the "Office" location in Azure AD & did a Bing Search and verified al accounts display the correct info, verified the info in Delve & Teams org chart
Performed all of the other same steps

Same results
No users or rooms were mapped
The details for the file, show all of my labels, but no user is mapped to them

**Comment by billdiekmann** [comment]
Correction

I ran another attempt and mapping process was successful. Building 2, Floor 1, shows 15 "People Count"
This time when I "Selected your Building" and "Upload Floor Plan", the process autocompleted to "Ready to Go" (It automatically skipped the "Link office locations" & "Specify location patterns".

I have now published this and am waiting for the "See Building Location" link to appear in the AAD profile for the users.

**Comment by billdiekmann** [comment]
Success
Following the modified instructions from rasrivas-ms, I have been able to successfully build out employee & room locations (maps) and associate AAD user accounts.

I think the following information needs to be added to the documentation:
- Include the minimum user & location information (too many of us test these solutions first and we typically use a very small data set; like 1-3 so as to not waste time)
- Information on using Visio would be helpful. You can create a floorplan in Visio, with labels, and then save it as a .dwg file.
- Information in regards to the index timing. After populating the "Office" field, it took 12 hours for it to be found in Bing search. Also, after successfully publishing a floorplan, it took 18 hours for the link in Search to include the map information

-

**Comment by rasrivas-ms** [comment]
We are updating the documentation and will make sure we incorporate your feedback in the updates.

**Comment by billdiekmann** [comment]
It is resolved! Thank you
