### ISSUE TITLE
WHAT AN INSANELY BAD IDEA (am I missing something???)

### ISSUE THREAD

**Issue by mhmckee** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#82]
So you mean to tell me that now an employee can search what they think is their computer for "make acrobat searchable" and they could get web results pointing to an online conversion program and merrily upload confidential client information to an unknown third party site, thinking this is the company sanctioned way to do this?  Why would this feature EVER be on by default???  I HATE seeing web-based results in F'ing Cortana.  Look, not all of us are idiot gamers.  Some of us are doing serious CONFIDENTIAL WORK in, oh, say LAW FIRMS and now Microsoft decides to just bring outside search results and wrap them up in the same package as internal results, leaving the less sophisticated users, who have NO WARNING THIS IS COMING to misunderstand and possibly cause serious harm by possibly disclosing internal, confidential PRIVILAGED information???????   I just can't believe the stupidity at Microsoft.  Does anyone ever think anything through?????    

Maybe turn this on by default in Windows Home baby crib edition but NOT for work environments!!!!   Not every company can afford a staff constantly reading and second guessing the plethora of changes coming from Microsoft.  HOLY CRAP YOU DUMBASSES!   (Red Forman scowl).  

Please tell me I'm missing something and I am the dumbass.  I would feel MUCH better.  

No wonder we have no corporate secrets anymore.  Shit this is the last straw I'm writing that article to the NY Times.  I've been a computer consultant to law firms for 30 years and this takes the freakin' cake!!!!!!!!!!  

Can someone tell me who I should evisvcerate for this bright idea?  I suspect this is not the correct forum but there is a link in the Microsoft Docs page called "submit feedback" re: "this product" so here it is!

**Comment by jeffkizn** [comment]
Thank you for that passionate feedback. You have not quite called it out, but I assume you're talking about the Windows search box as well as the integration with Cortana for finding and task completion skills. Often, finding information and completing tasks, even in a corporate environment spans both internal and external resources. Rather than continually context switch, our goal is to meet individuals where they are (the app) and bring them the information they need there. Cortana makes this even easier. 

Within all of this, we aim to give organizations control over their experiences, including feature toggles. In this case, the IT admin can disable Cortana integration with Bing Answers and more.
