### ISSUE TITLE
Document:  Microsoft Search not available to B2B users

### ISSUE THREAD

**Issue by JohnHuschka** [MicrosoftDocs/OfficeDocs-MicrosoftSearch#88]
Unless I'm missing it (apologize if I am), it is not documented anywhere (like [here](https://docs.microsoft.com/en-us/microsoftsearch/overview-microsoft-search)) that guest B2B users will be unable to access Microsoft Search (per my support ticket with Microsoft Support).  I know, in particular, within SharePoint, the suite bar search bar does not appear and all the guest B2B user sees is a legacy search experience.   Confusing to have a site that has one search experience for internal users and another for the guest B2B users with whom they are collaborating.

**Comment by jeffkizn** [comment]
Guest users can search in libraries, lists, sites, folders that are shared with them. They will never get answers, personalized results, or personalized suggestions. With this, the search box renders on the page rather than the header. We will look to make this clearer in either the [FAQ](https://docs.microsoft.com/en-us/microsoftsearch/faqs) page or the [Microsoft Search in SharePoint page](https://docs.microsoft.com/en-us/microsoftsearch/get-started-search-in-sharepoint-online)

**Comment by jeffkizn** [comment]
@JohnHuschka, we have updated the[ FAQ page](https://docs.microsoft.com/microsoftsearch/faqs) with a note on guest users. 

Can guest users leverage Microsoft Search in my organization?
Microsoft 365 enables rich collaboration with people outside of your organization through guest access. These users will be able to perform search operations on documents, sites, groups, lists, and libraries. However, guest users will not get the full, personalized, Microsoft Search experience and may need to leverage the on-page search box instead of the unified Microsoft Search box in the header.

**Comment by JohnHuschka** [comment]
@jeffkizn :  Nice doc job!  Thanks for the follow-up, action!  J
